#!/bin/bash
script_base_folder=$(dirname "$0")
[ ! -e "${script_base_folder}/onedrive" ] && echo 'Error! Not found 'onedrive'' && exit 1

function get_local_folder() {
    IFS=$'\n'
    for local_name in `ls -1 .`
      do
        if [[ -d $local_name ]]; then
          eval cd \'$local_name\'
          get_local_folder;
          cd ..
        else
          local_folder_name_tmp="$(echo "$(pwd)" |sed 's|'$local_folder_pre'||' |sed 's|^/||')"
          eval "${script_base_folder}/onedrive" -f \'$local_folder_name_tmp\' \'$local_name\'
        fi
      done
    }

local_folder="$1"
dir -d "${local_folder}" >/dev/null 2>&1;
[ $? -ne '0' ] && echo 'Error! Not access to the folder.' && exit 1
cd "${local_folder}"
local_folder_pre=`dirname "$(pwd)"`
local_folder_base=`basename "$(pwd)"`
eval "${script_base_folder}/onedrive" -c \'$local_folder_base\'
get_local_folder;
